// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/mage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level   uint32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Element string `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Health  uint32 `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
	Mana    uint32 `protobuf:"varint,5,opt,name=mana,proto3" json:"mana,omitempty"`
}

func (x *Mage) Reset() {
	*x = Mage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mage) ProtoMessage() {}

func (x *Mage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mage.ProtoReflect.Descriptor instead.
func (*Mage) Descriptor() ([]byte, []int) {
	return file_proto_mage_proto_rawDescGZIP(), []int{0}
}

func (x *Mage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mage) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Mage) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

func (x *Mage) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Mage) GetMana() uint32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

var File_proto_mage_proto protoreflect.FileDescriptor

var file_proto_mage_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x04, 0x4d, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x61, 0x6e,
	0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mage_proto_rawDescOnce sync.Once
	file_proto_mage_proto_rawDescData = file_proto_mage_proto_rawDesc
)

func file_proto_mage_proto_rawDescGZIP() []byte {
	file_proto_mage_proto_rawDescOnce.Do(func() {
		file_proto_mage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mage_proto_rawDescData)
	})
	return file_proto_mage_proto_rawDescData
}

var file_proto_mage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_mage_proto_goTypes = []interface{}{
	(*Mage)(nil), // 0: proto.Mage
}
var file_proto_mage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mage_proto_init() }
func file_proto_mage_proto_init() {
	if File_proto_mage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mage_proto_goTypes,
		DependencyIndexes: file_proto_mage_proto_depIdxs,
		MessageInfos:      file_proto_mage_proto_msgTypes,
	}.Build()
	File_proto_mage_proto = out.File
	file_proto_mage_proto_rawDesc = nil
	file_proto_mage_proto_goTypes = nil
	file_proto_mage_proto_depIdxs = nil
}
